language: node_js

node_js:
  - 5

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

before_script:
  - npm install -g bower
  - bower install
script: TEST_SERVER_PORT=8090 npm test
